version: '3.4'

services:
  api-gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API-Gateway/Dockerfile
    depends_on: 
      - tweet-service
      - trend-service
      - user-service

  tweet-service:
    image: ${DOCKER_REGISTRY-}tweetservice
    build:
      context: .
      dockerfile: tweet-service/Dockerfile
  
  s65user:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: admin
    volumes:
      - s65user-data:/var/lib/postgresql/data
    ports:
      - 5431:5432

  s65tweet:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: admin
    volumes:
      - s65tweet-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  s65trend:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: admin
    volumes:
      - s65trend-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
  
  trend-service:
    image: ${DOCKER_REGISTRY-}trendservice
    build:
      context: .
      dockerfile: trend-service/Dockerfile


  user-service:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: user-service/Dockerfile

  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "trend_topic:1:1;delete_user_topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

volumes:
  s65user-data:
    driver: local
  s65tweet-data:
    driver: local
  s65trend-data:
    driver: local