name: gateway-workflow
on:
  push:
    branches: [ master ]
    paths:
      - API-Gateway/**
      - .github/workflows/api-gateway.yml
  pull_request:
    branches: [ master ]
    paths:
      - API-Gateway/**
      - .github/workflows/api-gateway.yml

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: API-Gateway
    - name: Build
      run: dotnet build --no-restore 
      working-directory: API-Gateway
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: API-Gateway
    - name: Login Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: Build and Push Image
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with:
        image: emalajheer/api-gateway
        tags: latest
        registry: docker.io
        dockerfile: API-Gateway/Dockerfile
        directory: .
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
