name: trend-workflow
on:
  push:
    branches: [ master ]
    paths:
      - trend-service/**
      - .github/workflows/trend-service.yml
  pull_request:
    branches: [ master ]
    paths:
      - trend-service/**
      - .github/workflows/trend-service.yml

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: trend-service
    - name: Build
      run: dotnet build --no-restore 
      working-directory: trend-service
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: trend-service
    - name: Login Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: Build and Push Image
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with:
        image: emalajheer/trend-service
        tags: latest
        registry: docker.io
        dockerfile: trend-service/Dockerfile
        directory: .
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
