name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - tweet-service/**
      - .github/workflows/tweet-service.yml
  pull_request:
    branches: [ master ]
    paths:
      - tweet-service/**
      - .github/workflows/tweet-service.yml

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: tweet-service
    - name: Build
      run: dotnet build --no-restore 
      working-directory: tweet-service
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: tweet-service
    - name: Login Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ././tweet-service/Dockerfile
        push: true
        tags: emalajheer/tweet-service/tweet-service:latest
    - name: Docker Push
      run: docker push emalajheer/tweet-service:latest

      
